# Autogenerated by SmartBody
# -------------------- cameras
print "Save Cameras"
obj = scene.getCamera("cameraDefault")
if obj == None:
	obj = scene.createCamera("cameraDefault")
obj.setEye(0.283569, 2.31717, 48.2763)
obj.setCenter(0.216, 1, 45.86)
obj.setUpVector(SrVec(0, 1, 0))
obj.setScale(1)
obj.setFov(1.0472)
obj.setFarPlane(10000)
obj.setNearPlane(0.1)
obj.setAspectRatio(1.15481)
if obj.getAttribute("aspectRatio") != None :
	obj.setDoubleAttribute("aspectRatio",1.15481)
else:
	attr = obj.createDoubleAttribute("aspectRatio", 1.15481, True, "Camera", 270, False, False, False, "")
	attr.setDefaultValue(1)
	attr.setValue(1.15481)
if obj.getAttribute("blendTexturesWithLighting") != None :
	obj.setBoolAttribute("blendTexturesWithLighting",True)
else:
	attr = obj.createBoolAttribute("blendTexturesWithLighting", True, True, "Display", 405, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("centerX") != None :
	obj.setDoubleAttribute("centerX",0.216)
else:
	attr = obj.createDoubleAttribute("centerX", 0.216, True, "Camera", 200, False, False, False, "")
	attr.setDefaultValue(1)
	attr.setValue(0.216)
if obj.getAttribute("centerY") != None :
	obj.setDoubleAttribute("centerY",1)
else:
	attr = obj.createDoubleAttribute("centerY", 1, True, "Camera", 210, False, False, False, "")
	attr.setDefaultValue(1)
	attr.setValue(1)
if obj.getAttribute("centerZ") != None :
	obj.setDoubleAttribute("centerZ",45.86)
else:
	attr = obj.createDoubleAttribute("centerZ", 45.86, True, "Camera", 220, False, False, False, "")
	attr.setDefaultValue(1)
	attr.setValue(45.86)
if obj.getAttribute("collisionShape") != None :
	obj.setStringAttribute("collisionShape","null")
else:
	attr = obj.createStringAttribute("collisionShape",  "null", True, "Physics", 350, False, False, False, "Initializes the pawn as a physics object.")
	attr.setDefaultValue("null")
	attr.setValue("null")
	validValues = StringVec()
	validValues.append("null")
	validValues.append("sphere")
	validValues.append("box")
	validValues.append("capsule")
	attr.setValidValues(validValues)
if obj.getAttribute("collisionShapeScale") != None :
	obj.setVec3Attribute("collisionShapeScale",1, 1, 1)
else:
	attr = obj.createVec3Attribute("collisionShapeScale",  1, 1, 1, True, "Physics", 360, False, False, False, "Scaling of physics-based shape.")
	vec = SrVec()
	vec.setData(0, 1)
	vec.setData(1, 1)
	vec.setData(2, 1)
	attr.setDefaultValue(vec)
	vec1 = SrVec(1, 1, 1)
	attr.setValue(vec1)
if obj.getAttribute("createPhysics") == None :
	attr = obj.createActionAttribute("createPhysics",  True, "Physics", 300, False, False, False, "Initializes the pawn as a physics object.")
if obj.getAttribute("enablePhysics") != None :
	obj.setBoolAttribute("enablePhysics",False)
else:
	attr = obj.createBoolAttribute("enablePhysics", False, True, "Physics", 310, False, False, False, "Enables or disables physics for this pawn.")
	attr.setDefaultValue(False)
	attr.setValue(False)
if obj.getAttribute("far") != None :
	obj.setDoubleAttribute("far",10000)
else:
	attr = obj.createDoubleAttribute("far", 10000, True, "Camera", 260, False, False, False, "")
	attr.setDefaultValue(1)
	attr.setValue(10000)
if obj.getAttribute("fov") != None :
	obj.setDoubleAttribute("fov",1.0472)
else:
	attr = obj.createDoubleAttribute("fov", 1.0472, True, "Camera", 240, False, False, False, "")
	attr.setDefaultValue(1)
	attr.setValue(1.0472)
if obj.getAttribute("mesh") != None :
	obj.setStringAttribute("mesh","")
else:
	attr = obj.createStringAttribute("mesh",  "", True, "Display", 405, False, False, False, "Geometry/mesh")
	attr.setDefaultValue("")
	attr.setValue("")
	validValues = StringVec()
	attr.setValidValues(validValues)
if obj.getAttribute("meshRotation") != None :
	obj.setVec3Attribute("meshRotation",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshRotation",  0, 0, 0, True, "Display", 430, False, False, False, "Mesh rotation offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("meshScale") != None :
	obj.setDoubleAttribute("meshScale",1)
else:
	attr = obj.createDoubleAttribute("meshScale", 1, True, "Display", 400, False, False, False, "Scale of geometry/mesh")
	attr.setDefaultValue(1)
	attr.setValue(1)
if obj.getAttribute("meshTranslate") != None :
	obj.setVec3Attribute("meshTranslate",0, 0, 0)
else:
	attr = obj.createVec3Attribute("meshTranslate",  0, 0, 0, True, "Display", 420, False, False, False, "Mesh translation offset")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 0)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 0, 0)
	attr.setValue(vec1)
if obj.getAttribute("near") != None :
	obj.setDoubleAttribute("near",0.1)
else:
	attr = obj.createDoubleAttribute("near", 0.1, True, "Camera", 250, False, False, False, "")
	attr.setDefaultValue(1)
	attr.setValue(0.1)
if obj.getAttribute("posX") != None :
	obj.setDoubleAttribute("posX",0.283569)
else:
	attr = obj.createDoubleAttribute("posX", 0.283569, True, "transform", 10, False, False, False, "X position")
	attr.setDefaultValue(0)
	attr.setValue(0.283569)
if obj.getAttribute("posY") != None :
	obj.setDoubleAttribute("posY",2.31717)
else:
	attr = obj.createDoubleAttribute("posY", 2.31717, True, "transform", 20, False, False, False, "Y position")
	attr.setDefaultValue(0)
	attr.setValue(2.31717)
if obj.getAttribute("posZ") != None :
	obj.setDoubleAttribute("posZ",48.2763)
else:
	attr = obj.createDoubleAttribute("posZ", 48.2763, True, "transform", 30, False, False, False, "Z position")
	attr.setDefaultValue(0)
	attr.setValue(48.2763)
if obj.getAttribute("rotX") != None :
	obj.setDoubleAttribute("rotX",-30.5448)
else:
	attr = obj.createDoubleAttribute("rotX", -30.5448, True, "transform", 40, False, False, False, "X rotation")
	attr.setDefaultValue(0)
	attr.setValue(-30.5448)
if obj.getAttribute("rotY") != None :
	obj.setDoubleAttribute("rotY",1.09009)
else:
	attr = obj.createDoubleAttribute("rotY", 1.09009, True, "transform", 50, False, False, False, "Y rotation")
	attr.setDefaultValue(0)
	attr.setValue(1.09009)
if obj.getAttribute("rotZ") != None :
	obj.setDoubleAttribute("rotZ",1.31245e-009)
else:
	attr = obj.createDoubleAttribute("rotZ", 1.31245e-009, True, "transform", 60, False, False, False, "Z rotation")
	attr.setDefaultValue(0)
	attr.setValue(1.31245e-009)
if obj.getAttribute("scale") != None :
	obj.setDoubleAttribute("scale",1)
else:
	attr = obj.createDoubleAttribute("scale", 1, True, "Camera", 280, False, False, False, "")
	attr.setDefaultValue(1)
	attr.setValue(1)
if obj.getAttribute("showStaticMesh") != None :
	obj.setBoolAttribute("showStaticMesh",True)
else:
	attr = obj.createBoolAttribute("showStaticMesh", True, True, "Display", 415, False, False, False, "Whether the object is visible.")
	attr.setDefaultValue(True)
	attr.setValue(True)
if obj.getAttribute("up") != None :
	obj.setVec3Attribute("up",0, 1, 0)
else:
	attr = obj.createVec3Attribute("up",  0, 1, 0, True, "Camera", 230, False, False, False, "")
	vec = SrVec()
	vec.setData(0, 0)
	vec.setData(1, 1)
	vec.setData(2, 0)
	attr.setDefaultValue(vec)
	vec1 = SrVec(0, 1, 0)
	attr.setValue(vec1)
if obj.getAttribute("visible") != None :
	obj.setBoolAttribute("visible",False)
else:
	attr = obj.createBoolAttribute("visible", False, True, "Display", 5, False, False, False, "")
	attr.setDefaultValue(True)
	attr.setValue(False)
